on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '4.0'

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool pkg-config build-essential libssl-dev
      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Cache vendored ports
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: tmp
          key: ports-${{ runner.os }}-ngtcp2-1.25.0-picotls-f07f1c8-${{ hashFiles('ext/quic/extconf.rb', 'ext/quic/patches/**') }}
      - name: Run the default task
        run: bundle exec rake
